[project]
name = "bitcoin-explorer"
version = "1.2.19"
description = "High Performance Blockchain Deserializer"
long_description_content_type="text/markdown"
readme = "README.md"
homepage = 'https://github.com/Congyuwang/Py-Bitcoin-Explorer'
repository = 'https://github.com/Congyuwang/Py-Bitcoin-Explorer'
documentation = 'https://congyuwang.github.io/Py-Bitcoin-Explorer/bitcoin_explorer.html'

keywords = ["rust", "bitcoin", "blockchain", "deserialize",
    "parser", "explorer", "crypto", "transaction"]

[package.metadata.maturin]
python-source = "bitcoin_explorer"

classifiers=[
    "Programming Language :: Rust",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]

[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.maturin]
python-source = "bitcoin_explorer"
